//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accountdata()
        {
            this.userdata = new HashSet<userdata>();
        }
    
        public int IdAD { get; set; }
        public System.DateTime RegistrateTimeAD { get; set; }
        public string UserNameAD { get; set; }
        public string PasswordAD { get; set; }
        public string PassSaltAD { get; set; }
        public int PriviledgesIdAD { get; set; }
        public bool VerifiedByAdminAD { get; set; }
        public bool DeletedAD { get; set; }
        public Nullable<System.DateTime> DeletedTimeAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userdata> userdata { get; set; }
        public virtual priviledges_fx priviledges_fx { get; set; }
    }
}
