//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class companydata
    {
        public int IdCD { get; set; }
        public string NameCD { get; set; }
        public int ZipCodeCD { get; set; }
        public int SettlementCD { get; set; }
        public string AddressCD { get; set; }
        public string TAXNumberCD { get; set; }
        public string RegistrationNumberCD { get; set; }
        public string InvoiceNumberCD { get; set; }
        public string PhoneCD { get; set; }
        public string EmailCD { get; set; }
        public string WebPageCD { get; set; }
    
        public virtual settlement_fx settlement_fx { get; set; }
        public virtual zipcode_fx zipcode_fx { get; set; }
    }
}
