//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class currentpricesforeachbill_st
    {
        public int IdB { get; set; }
        public int IdPFS { get; set; }
        public Nullable<bool> Dummy { get; set; }
    
        public virtual billing billing { get; set; }
        public virtual pricesforeachservice pricesforeachservice { get; set; }
    }
}
