//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicalEntities : DbContext
    {
        public medicalEntities()
            : base("name=medicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountdata> accountdata { get; set; }
        public virtual DbSet<belong_st> belong_st { get; set; }
        public virtual DbSet<billing> billing { get; set; }
        public virtual DbSet<companydata> companydata { get; set; }
        public virtual DbSet<currentpricesforeachbill_st> currentpricesforeachbill_st { get; set; }
        public virtual DbSet<evidencedata> evidencedata { get; set; }
        public virtual DbSet<evidencedatadocuments> evidencedatadocuments { get; set; }
        public virtual DbSet<evidencedatadocuments_st> evidencedatadocuments_st { get; set; }
        public virtual DbSet<examinationdata> examinationdata { get; set; }
        public virtual DbSet<examinationdatadocuments> examinationdatadocuments { get; set; }
        public virtual DbSet<examinationdatadocuments_st> examinationdatadocuments_st { get; set; }
        public virtual DbSet<examinationeachevidence_st> examinationeachevidence_st { get; set; }
        public virtual DbSet<examinationeachimportedevidence_st> examinationeachimportedevidence_st { get; set; }
        public virtual DbSet<exceptedschedule> exceptedschedule { get; set; }
        public virtual DbSet<gender_fx> gender_fx { get; set; }
        public virtual DbSet<importedevidencedata> importedevidencedata { get; set; }
        public virtual DbSet<importedevidencedatadocuments_st> importedevidencedatadocuments_st { get; set; }
        public virtual DbSet<importedexaminationdata> importedexaminationdata { get; set; }
        public virtual DbSet<importedexaminationdatadocuments_st> importedexaminationdatadocuments_st { get; set; }
        public virtual DbSet<importedexaminationeachevidence_st> importedexaminationeachevidence_st { get; set; }
        public virtual DbSet<importedexaminationeachimportedevidence_st> importedexaminationeachimportedevidence_st { get; set; }
        public virtual DbSet<newperson> newperson { get; set; }
        public virtual DbSet<patientdata> patientdata { get; set; }
        public virtual DbSet<pricesforeachservice> pricesforeachservice { get; set; }
        public virtual DbSet<priviledges_fx> priviledges_fx { get; set; }
        public virtual DbSet<scheduledata> scheduledata { get; set; }
        public virtual DbSet<scheduleperson_st> scheduleperson_st { get; set; }
        public virtual DbSet<servicesdata> servicesdata { get; set; }
        public virtual DbSet<settlement_fx> settlement_fx { get; set; }
        public virtual DbSet<settlementzipcode_st> settlementzipcode_st { get; set; }
        public virtual DbSet<status_fx> status_fx { get; set; }
        public virtual DbSet<userdata> userdata { get; set; }
        public virtual DbSet<usersschedule> usersschedule { get; set; }
        public virtual DbSet<zipcode_fx> zipcode_fx { get; set; }
    }
}
