//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medicalEntities : DbContext
    {
        public medicalEntities()
            : base("name=medicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountdata> accountdata { get; set; }
        public virtual DbSet<belong_st> belong_st { get; set; }
        public virtual DbSet<companydata> companydata { get; set; }
        public virtual DbSet<doctorschedule> doctorschedule { get; set; }
        public virtual DbSet<evidencedata> evidencedata { get; set; }
        public virtual DbSet<examinationdata> examinationdata { get; set; }
        public virtual DbSet<examinationseachevidence_st> examinationseachevidence_st { get; set; }
        public virtual DbSet<gender_fx> gender_fx { get; set; }
        public virtual DbSet<patientdata> patientdata { get; set; }
        public virtual DbSet<priviledges_fx> priviledges_fx { get; set; }
        public virtual DbSet<scheduledata> scheduledata { get; set; }
        public virtual DbSet<settlement_fx> settlement_fx { get; set; }
        public virtual DbSet<settlementzipcode_st> settlementzipcode_st { get; set; }
        public virtual DbSet<status_fx> status_fx { get; set; }
        public virtual DbSet<treatmentdata> treatmentdata { get; set; }
        public virtual DbSet<userdata> userdata { get; set; }
        public virtual DbSet<zipcode_fx> zipcode_fx { get; set; }
    }
}
