//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorschedule
    {
        public int IdDS { get; set; }
        public int UserDataIdDS { get; set; }
        public System.DateTime DateDS { get; set; }
        public System.TimeSpan StartTimeDS { get; set; }
        public System.TimeSpan FinishTimeDS { get; set; }
    
        public virtual userdata userdata { get; set; }
    }
}
