//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencedata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evidencedata()
        {
            this.evidencedatadocuments_st = new HashSet<evidencedatadocuments_st>();
            this.examinationeachevidence_st = new HashSet<examinationeachevidence_st>();
            this.importedexaminationeachevidence_st = new HashSet<importedexaminationeachevidence_st>();
        }
    
        public int IdED { get; set; }
        public int PatientIdED { get; set; }
        public int UserDataIdED { get; set; }
        public Nullable<int> ScheduleIdED { get; set; }
        public System.DateTime DateTimeED { get; set; }
        public string CodeED { get; set; }
    
        public virtual userdata userdata { get; set; }
        public virtual patientdata patientdata { get; set; }
        public virtual scheduledata scheduledata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencedatadocuments_st> evidencedatadocuments_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationeachevidence_st> examinationeachevidence_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationeachevidence_st> importedexaminationeachevidence_st { get; set; }
    }
}
