//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencedata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evidencedata()
        {
            this.evidencedata_st = new HashSet<evidencedata_st>();
            this.importedexaminationseachevidence_st = new HashSet<importedexaminationseachevidence_st>();
            this.examinationseachevidence_st = new HashSet<examinationseachevidence_st>();
        }
    
        public int IdED { get; set; }
        public int PatientIdED { get; set; }
        public int UserDataIdED { get; set; }
        public Nullable<int> ScheduleIdED { get; set; }
        public System.DateTime DateTimeED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencedata_st> evidencedata_st { get; set; }
        public virtual userdata userdata { get; set; }
        public virtual patientdata patientdata { get; set; }
        public virtual scheduledata scheduledata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationseachevidence_st> importedexaminationseachevidence_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationseachevidence_st> examinationseachevidence_st { get; set; }
    }
}
