//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencedatadocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evidencedatadocuments()
        {
            this.evidencedatadocuments_st = new HashSet<evidencedatadocuments_st>();
            this.importedevidencedatadocuments_st = new HashSet<importedevidencedatadocuments_st>();
        }
    
        public int IdEDD { get; set; }
        public byte[] DataEDD { get; set; }
        public string TypeEDD { get; set; }
        public string FileTypeEDD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencedatadocuments_st> evidencedatadocuments_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedevidencedatadocuments_st> importedevidencedatadocuments_st { get; set; }
    }
}
