//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class examinationdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public examinationdata()
        {
            this.examinationdatadocuments_st = new HashSet<examinationdatadocuments_st>();
            this.examinationeachevidence_st = new HashSet<examinationeachevidence_st>();
            this.examinationeachimportedevidence_st = new HashSet<examinationeachimportedevidence_st>();
        }
    
        public int IdEX { get; set; }
        public int PatientIdEX { get; set; }
        public int DoctorIdEX { get; set; }
        public System.DateTime DateTimeEX { get; set; }
        public int TreatmentIdEX { get; set; }
        public string CodeEX { get; set; }
        public int CompanyIdEX { get; set; }
    
        public virtual companydata companydata { get; set; }
        public virtual patientdata patientdata { get; set; }
        public virtual treatmentdata treatmentdata { get; set; }
        public virtual userdata userdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationdatadocuments_st> examinationdatadocuments_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationeachevidence_st> examinationeachevidence_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationeachimportedevidence_st> examinationeachimportedevidence_st { get; set; }
    }
}
