//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class importedevidencedata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public importedevidencedata()
        {
            this.examinationeachimportedevidence_st = new HashSet<examinationeachimportedevidence_st>();
            this.importedevidencedatadocuments_st = new HashSet<importedevidencedatadocuments_st>();
            this.importedexaminationeachimportedevidence_st = new HashSet<importedexaminationeachimportedevidence_st>();
        }
    
        public int IdIED { get; set; }
        public int PatientIED { get; set; }
        public int UserDataIdIED { get; set; }
        public System.DateTime DateTimeIED { get; set; }
        public string CodeIED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationeachimportedevidence_st> examinationeachimportedevidence_st { get; set; }
        public virtual patientdata patientdata { get; set; }
        public virtual userdata userdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedevidencedatadocuments_st> importedevidencedatadocuments_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationeachimportedevidence_st> importedexaminationeachimportedevidence_st { get; set; }
    }
}
