//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class importedexaminationdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public importedexaminationdata()
        {
            this.importedexaminationdatadocuments_st = new HashSet<importedexaminationdatadocuments_st>();
            this.importedexaminationeachevidence_st = new HashSet<importedexaminationeachevidence_st>();
            this.importedexaminationeachimportedevidence_st = new HashSet<importedexaminationeachimportedevidence_st>();
        }
    
        public int IdIEX { get; set; }
        public int PatientIdIEX { get; set; }
        public int DoctorIdIEX { get; set; }
        public System.DateTime DateTimeIEX { get; set; }
        public string NameIEX { get; set; }
        public string CodeIEX { get; set; }
        public int CompanyIdIEX { get; set; }
    
        public virtual companydata companydata { get; set; }
        public virtual patientdata patientdata { get; set; }
        public virtual userdata userdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationdatadocuments_st> importedexaminationdatadocuments_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationeachevidence_st> importedexaminationeachevidence_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationeachimportedevidence_st> importedexaminationeachimportedevidence_st { get; set; }
    }
}
