//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class importedexaminationdata_st
    {
        public int IdIEX { get; set; }
        public int IdEXD { get; set; }
        public Nullable<bool> Dummy { get; set; }
    
        public virtual examinationdatadocuments examinationdatadocuments { get; set; }
        public virtual importedexaminationdata importedexaminationdata { get; set; }
    }
}
