//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class importedexaminationdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public importedexaminationdata()
        {
            this.importedexaminationdata_st = new HashSet<importedexaminationdata_st>();
            this.importedexaminationseachevidence_st = new HashSet<importedexaminationseachevidence_st>();
            this.importedexaminatioseachimportedevidence_st = new HashSet<importedexaminatioseachimportedevidence_st>();
        }
    
        public int IdIEX { get; set; }
        public int PatientIdIEX { get; set; }
        public System.DateTime DateTimeIEX { get; set; }
        public string NameIED { get; set; }
    
        public virtual patientdata patientdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationdata_st> importedexaminationdata_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminationseachevidence_st> importedexaminationseachevidence_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminatioseachimportedevidence_st> importedexaminatioseachimportedevidence_st { get; set; }
    }
}
