//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class importedevidencedata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public importedevidencedata()
        {
            this.examinationseachimportedevidence = new HashSet<examinationseachimportedevidence>();
            this.importedevidencedata_st = new HashSet<importedevidencedata_st>();
            this.importedexaminatioseachimportedevidence_st = new HashSet<importedexaminatioseachimportedevidence_st>();
        }
    
        public int IdIED { get; set; }
        public int PatientIED { get; set; }
        public System.DateTime DateTimeIED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinationseachimportedevidence> examinationseachimportedevidence { get; set; }
        public virtual patientdata patientdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedevidencedata_st> importedevidencedata_st { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<importedexaminatioseachimportedevidence_st> importedexaminatioseachimportedevidence_st { get; set; }
    }
}
