//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricesforeachservice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pricesforeachservice()
        {
            this.currentpricesforeachbill_st = new HashSet<currentpricesforeachbill_st>();
        }
    
        public int IdPFS { get; set; }
        public int VatPFS { get; set; }
        public int PricePFS { get; set; }
        public int ServiceDataIdPFS { get; set; }
        public System.DateTime WhenChangedPFS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<currentpricesforeachbill_st> currentpricesforeachbill_st { get; set; }
        public virtual servicesdata servicesdata { get; set; }
    }
}
