//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class priviledges_fx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public priviledges_fx()
        {
            this.accountdata = new HashSet<accountdata>();
        }
    
        public int IdP { get; set; }
        public string NameP { get; set; }
        public bool ScheduleP { get; set; }
        public bool PatientP { get; set; }
        public bool ExaminationP { get; set; }
        public bool LabP { get; set; }
        public bool EvidenceP { get; set; }
        public bool PrescriptionP { get; set; }
        public bool BillingP { get; set; }
        public bool StatisticP { get; set; }
        public bool UsersP { get; set; }
        public bool SettingP { get; set; }
        public bool HelpP { get; set; }
        public bool LogoutP { get; set; }
        public bool AllSeeP { get; set; }
        public bool IsDoctorP { get; set; }
        public bool IncludeScheduleP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accountdata> accountdata { get; set; }
    }
}
