//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduledata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scheduledata()
        {
            this.evidencedata = new HashSet<evidencedata>();
        }
    
        public int IdSD { get; set; }
        public int PatientIdSD { get; set; }
        public int DoctorIdSD { get; set; }
        public System.DateTime StartSD { get; set; }
        public System.DateTime FinishSD { get; set; }
        public Nullable<int> StatusSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencedata> evidencedata { get; set; }
        public virtual patientdata patientdata { get; set; }
        public virtual userdata userdata { get; set; }
        public virtual status_fx status_fx { get; set; }
    }
}
