//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduleperson_st
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scheduleperson_st()
        {
            this.scheduledata = new HashSet<scheduledata>();
        }
    
        public int IdSP { get; set; }
        public bool WhereSP { get; set; }
        public Nullable<int> NewPersonIdSP { get; set; }
        public Nullable<int> ExistedIdSP { get; set; }
    
        public virtual newperson newperson { get; set; }
        public virtual patientdata patientdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduledata> scheduledata { get; set; }
    }
}
