//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduledata
    {
        public int IdSD { get; set; }
        public bool StillNotVisitedSD { get; set; }
        public int PatientIdSD { get; set; }
        public System.DateTime StartSD { get; set; }
        public System.DateTime FinishSD { get; set; }
        public Nullable<int> DoctorIdSD { get; set; }
        public string NotesSD { get; set; }
        public int StatusSD { get; set; }
    
        public virtual userdata userdata { get; set; }
        public virtual scheduleperson_st scheduleperson_st { get; set; }
        public virtual status_fx status_fx { get; set; }
    }
}
