//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class settlementzipcode_st
    {
        public int IdZC { get; set; }
        public int IdS { get; set; }
        public Nullable<bool> Dummy { get; set; }
    
        public virtual settlement_fx settlement_fx { get; set; }
        public virtual zipcode_fx zipcode_fx { get; set; }
    }
}
