//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAdministrationSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersschedule
    {
        public int IdUS { get; set; }
        public int UserDataIdUS { get; set; }
        public int DayOfWeekUS { get; set; }
        public System.DateTime StartTimeUS { get; set; }
        public System.DateTime FinishTimeUS { get; set; }
    
        public virtual userdata userdata { get; set; }
    }
}
